/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : Role,
  'timestamp' : IDL.Int,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'createdAt' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Nat, Role, IDL.Text], [IDL.Nat], []),
  'autoGenerateTitle' : IDL.Func([IDL.Nat], [], []),
  'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteConversation' : IDL.Func([IDL.Nat], [], []),
  'getConversation' : IDL.Func([IDL.Nat], [Conversation], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateConversationTitle' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : Role,
    'timestamp' : IDL.Int,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'createdAt' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Nat, Role, IDL.Text], [IDL.Nat], []),
    'autoGenerateTitle' : IDL.Func([IDL.Nat], [], []),
    'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteConversation' : IDL.Func([IDL.Nat], [], []),
    'getConversation' : IDL.Func([IDL.Nat], [Conversation], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'listConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateConversationTitle' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };