/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Message {
    id: bigint;
    content: string;
    role: Role;
    timestamp: bigint;
}
export interface Conversation {
    id: bigint;
    title: string;
    messages: Array<Message>;
    createdAt: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export enum Role {
    user = "user",
    assistant = "assistant"
}
export interface backendInterface {
    addMessage(conversationId: bigint, role: Role, content: string): Promise<bigint>;
    autoGenerateTitle(conversationId: bigint): Promise<void>;
    createConversation(title: string): Promise<bigint>;
    deleteConversation(conversationId: bigint): Promise<void>;
    getConversation(conversationId: bigint): Promise<Conversation>;
    getMessages(conversationId: bigint): Promise<Array<Message>>;
    listConversations(): Promise<Array<Conversation>>;
    sendMessage(conversationId: bigint, userMessage: string): Promise<Message>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateConversationTitle(conversationId: bigint, title: string): Promise<void>;
}
import type { Conversation as _Conversation, Message as _Message, Role as _Role } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMessage(arg0: bigint, arg1: Role, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async autoGenerateTitle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.autoGenerateTitle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoGenerateTitle(arg0);
            return result;
        }
    }
    async createConversation(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConversation(arg0);
            return result;
        }
    }
    async deleteConversation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConversation(arg0);
            return result;
        }
    }
    async getConversation(arg0: bigint): Promise<Conversation> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_Conversation_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_Conversation_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConversations();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConversations();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: bigint, arg1: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return from_candid_Message_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return from_candid_Message_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateConversationTitle(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConversationTitle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConversationTitle(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Conversation_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    messages: Array<_Message>;
    createdAt: bigint;
}): {
    id: bigint;
    title: string;
    messages: Array<Message>;
    createdAt: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        messages: from_candid_vec_n5(_uploadFile, _downloadFile, value.messages),
        createdAt: value.createdAt
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    role: _Role;
    timestamp: bigint;
}): {
    id: bigint;
    content: string;
    role: Role;
    timestamp: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        role: from_candid_Role_n8(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): Role {
    return "user" in value ? Role.user : "assistant" in value ? Role.assistant : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    user: null;
} | {
    assistant: null;
} {
    return value == Role.user ? {
        user: null
    } : value == Role.assistant ? {
        assistant: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
